print(' Vamos fazer seu cadastro como cliente,')
print(' Por favor preencha os dados abaixo:')
print('')

nome = input ('Nome:')
print('')
idade = input ('Idade:')
print('')
nascimento = input ('Data de Nascimento DD/MM/ANO:')
print('')
cidade = input ('Cidade onde Nasceu:')
print('')
estado = input ('Estado Civil:')
print('')
cep = input ('CEP:')
print('')
rua = input ('Rua:')
print('')
numero = input('Numero da Resicencia:')
print('')
email = input ('Email de Cadastro:')
print('')
print('Confirmando os Dados')
print('')
print('')
print('Seus dados são')
print('Nome:' ,nome,)
print('')
print('Idade Atual:',idade,'anos')
print('')
print('Data de Nascimento:' ,nascimento,)
print('')
print('Cidade onde Nasceu:' ,cidade,)
print('')
print('Estado Civil:' ,estado,)
print('')
print('CEP:' ,cep,)
print('')
print('Rua:' ,rua,)
print('')
print('Numero da Residencia:' ,numero,)
print('')
print(' Email de cadastro:' ,email,)
print('')

nome, input ('AS informações estao corretas?')
print('')
print('')

print('Obrigado' ,nome, 'por se cadastrar em nosso site, tenha um otimo dia')
print('')
print('Em breve chegara um email com a confirmação de cadastro,')
print(' Não deixe de consultar sua caixa de entrada')
