nome = input ('Qual é o seu nome?')
print('Olá' ,nome,'!' ' seja bem vindo ao meu primeiro script')
idade = input ('Qual é a sua idade?')
print( idade,'anos !!!' ' vamos prosseguir para as proximas perguntas')
peso = input ('Qual é o seu peso?')
dia = input (' Que dia voçê nasceu?')
mes = input ('Em que mês voçê nasceu?')
ano = input ('Em qual ano voçê nasceu?')
print('Entao esses seus dados:' ,nome, idade, 'anos de idade', peso, 'Kg'',Nasceu dia' ,dia, 'do',mes,'de',ano)
